# Generated by Django 2.2.3 on 2019-08-26 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconnection',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userconnection',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
