# Generated by Django 2.2.3 on 2019-07-23 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('company_name', models.CharField(max_length=160, null=True)),
                ('company_address', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('tel', models.CharField(max_length=20, null=True)),
                ('url', models.TextField(null=True)),
                ('photo_url', models.TextField(null=True)),
                ('admin_name', models.CharField(max_length=50, null=True)),
                ('company_position', models.CharField(max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
